spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cinema?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-active: 200
    max-idle: 20
    min-idle: 10
  thymeleaf:
    cache: false
  jackson:
    time-zone: GMT+8
  messages:
    basename: i18n.login


mybatis:
  mapper-locations: classpath:dao/mapper/*/*Mapper.xml
